Update readme
Datastillery/smartcitiesdata pull request #1059
Opened 2020-10-31 05:20 UTC by sukaant

smartcitiesdata/scosopedia#279 co-authored-by: Matt Dunson dunson.142000@gmail.com

2020-11-02 14:05 UTC, dunson062786 requested changes

2020-11-02 14:05 UTC, dunson062786 commented on README.md
> +
Can we also update the content in these links. The directions only tell you how to install the software you'll need for the platform they don't actually give you directions on how to setup the environment.

2020-11-02 14:44 UTC, dunson062786 commented on README.md
> +
Can you include a link to https://github.com/Datastillery/smartcitiesdata/wiki/Run

2020-12-16 22:37 UTC, dunson062786 approved these changes

2020-12-18 14:14 UTC, JarredOlson commented on README.md
> +## To run E2E Test Locally
Use `End to End` instead of `E2E`

2020-12-18 14:14 UTC, JarredOlson commented on apps/discovery_api/README.md
> +  # TODO: Create a config/auth0.exs file and test it
Update or Remove TODO comment

2020-12-18 14:14 UTC, JarredOlson commented on apps/discovery_api/README.md
> +  * `MIX_ENV=integration mix docker.stop` (in this directory)
Let's call out that the above steps start it and this step stops it

2020-12-18 14:14 UTC, JarredOlson commented on apps/discovery_api/README.md
> +  * TODO: update this to include actual running the container
Update or Remove TODO comment

2020-12-18 14:14 UTC, JarredOlson commented on apps/discovery_api/README.md
> +<!--- TODO: Ask Jarred if he wants more details in the Tableau readme or if it is fine the way it is. -->
What is there is fine for now

2020-12-18 14:14 UTC, JarredOlson commented on apps/reaper/README.md
> +  * TODO: update this to include actual running the container
Update or Remove TODO

2020-12-21 21:23 UTC, merged